DeAnCNPMNC/DeAnCNPMNC/Models/Bill.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeAnCNPMNC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Bill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bill()
        {
            this.DetailBills = new HashSet<DetailBill>();
        }
    
        public int IDBill { get; set; }

        [DataType(DataType.Date)]
        public Nullable<System.DateTime> DateOrder { get; set; }
        public string AccCustomer { get; set; }
        public string CouponName { get; set; }
        public Nullable<double> TotalBill { get; set; }
        public string AddressCus { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Coupon Coupon { get; set; }
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailBill> DetailBills { get; set; }
    }
}

DeAnCNPMNC/DeAnCNPMNC/Areas/Admin/Controllers/BillController.cs
using DeAnCNPMNC.Models;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;

namespace DeAnCNPMNC.Areas.Admin.Controllers
{
    public class BillController : Controller
    {
        CNPMFastFoodEntities database = new CNPMFastFoodEntities();
        // GET: Admin/Bill
        public static List<Bill> SelectAllArticle()
        {
            var rtn = new List<Bill>();
            using (var context = new CNPMFastFoodEntities())
            {
                foreach (var item in context.Bills)
                {
                    rtn.Add(new Bill
                    {
                        IDBill = item.IDBill,
                        DateOrder = item.DateOrder,
                        AccCustomer = item.AccCustomer,
                        CouponName = item.CouponName,
                        TotalBill = item.TotalBill,
                        AddressCus = item.AddressCus,
                        Status = item.Status
                    }); ;
                }
            }
            return rtn;
        }
        public ActionResult DSBill()
        {
            var lsBill = SelectAllArticle().OrderByDescending(x => x.IDBill).ToList();
            return View(lsBill);
        }
        public ActionResult EditBill(int Id)
        {
            return View(database.Bills.Where(s => s.IDBill == Id).FirstOrDefault());
        }

        [HttpPost]
        public ActionResult EditBill(int Id, Bill bill)
        {
            database.Entry(bill).State = System.Data.Entity.EntityState.Modified;
            database.SaveChanges();
            bool status = Convert.ToBoolean(database.Bills.Where(s => s.IDBill == Id).FirstOrDefault().Status);
            string taikhoan = database.Bills.Where(s => s.IDBill == Id).FirstOrDefault().AccCustomer;
            string gmailkhach = database.Customers.Where(s => s.AccountCustomer == taikhoan).FirstOrDefault().EmailCustomer;
            if (status == true)
            {
                using (MailMessage mail = new MailMessage())
                {
                    mail.To.Add(gmailkhach);
                    mail.From = new MailAddress("nguyendaoduchuy2808@gmail.com");
                    mail.Subject = "Agent Fast Food";
                    mail.Body = "Đơn hàng của bạn đã được xác nhận!";
                    mail.IsBodyHtml = true;
                    using (SmtpClient smtp = new SmtpClient("smtp.gmail.com", 587))
                    {
                        smtp.UseDefaultCredentials = false;
                        smtp.DeliveryMethod = SmtpDeliveryMethod.Network;
                        smtp.Credentials = new NetworkCredential("nguyendaoduchuy2808@gmail.com", "01887220286Huy");
                        smtp.EnableSsl = true;
                        smtp.Send(mail);
                    }    
                }                        
            }    
            return RedirectToAction("DSBill");
        }

        public ActionResult DetailsNV(int Id)
        {
            var Details = database.DetailBills.Where(s => s.ID == Id).FirstOrDefault();
            return View(Details);
        }
        //public ActionResult Index()
        //{
        //    return View();
        //}
        //[HttpPost]
        public ActionResult DetailsAD(int Id)
        {
            var Details = database.DetailBills.Where(s => s.ID == Id).FirstOrDefault();
            return View(Details);
        }
        public ActionResult Index(string searchString, DateTime? date, DateTime? date1, int? Id)
        {
            var list = SelectAllArticle().OrderByDescending(x => x.IDBill).ToList();
            if (searchString == null && date == null)
            {
                list = SelectAllArticle().OrderByDescending(x => x.IDBill).ToList();
            }
            else if (searchString == null || date != null || date1 != null)
            {
                //var list = SelectAllArticle().Where(s => s.DateOrder.Value.Equals(date.Value));
                using (var context = new CNPMFastFoodEntities())
                {
                    list = context.Bills.SqlQuery("SELECT * FROM Bill where DateOrder BETWEEN '" + date.Value.ToString("yyyy/MM/dd", CultureInfo.InvariantCulture) + "' and '" + date1.Value.ToString("yyyy/MM/dd", CultureInfo.InvariantCulture) + "'").ToList();
                }
                Session["date"] = date.Value.ToString("yyyy/MM/dd", CultureInfo.InvariantCulture);
                Session["date1"] = date1.Value.ToString("yyyy/MM/dd", CultureInfo.InvariantCulture);
                return View(list);
            }
            return View(list);
        }
        //[HttpPost]
        //public ActionResult Tranfer()
        //{
        //    using (var context = new CNPMFastFoodEntities())
        //    {
        //        context.Database.ExecuteSqlCommand("INSERT INTO Revenue (RevenueDateStart, RevenueDateEnd, RevenueMoney) SELECT '" + Session["date"] + "', '" + Session["date1"] + "', SUM(IntoMoney) FROM Bill WHERE DateOrder BETWEEN '" + Session["date"] + "' and '" + Session["date1"] + "'");
        //        context.SaveChanges();
        //    }
        //    return View();
        //}
    }
}

DeAnCNPMNC/DeAnCNPMNC/Areas/Admin/Views/Bill/DSBill.cshtml
@model IEnumerable<DeAnCNPMNC.Models.Bill>

@{
    ViewBag.Title = "DSBill";
    Layout = "~/Areas/Admin/Views/Shared/_layoutquanly.cshtml";
}

<h2>Danh sách hóa đơn</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.IDBill)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateOrder)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AccCustomer)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AddressCus)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TotalBill)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IDBill)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateOrder)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AccCustomer)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AddressCus)
            </td>
            <td>
                @if (item.Status == true)
                {
                    <a>Đã phục vụ</a>
                }
                else
                {
                    <a>Chưa phục vụ</a>
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TotalBill)
            </td>
            <td>
                @*@Html.ActionLink("Sửa hóa đơn", "Edit", new { Id = item.IDBill }) |*@
                @Html.ActionLink("Sửa tình trạng", "EditBill", new { Id = item.IDBill }) |
                @Html.ActionLink("Chi tiết hóa đơn", "DetailsNV", new { Id = item.IDBill })
            </td>
        </tr>
    }

</table>

DeAnCNPMNC/DeAnCNPMNC/Areas/Admin/Views/Bill/DetailsAD.cshtml
@model DeAnCNPMNC.Models.DetailBill

@{
    ViewBag.Title = "DetailsAD";
    Layout = "~/Areas/Admin/Views/Shared/_layoutquanly.cshtml";
}

<div>
    <h1 class="col-12" style="text-align:center">Chi tiết hóa đơn</h1>
    <hr />

    @using (var context = new DeAnCNPMNC.Models.CNPMFastFoodEntities())
    {
        foreach (var item in context.DetailBills.Where(s => s.BillName.ToString().Contains(Model.ID.ToString())).ToList())
        {
            <div class="col-12" style="text-align:center">
                <a>
                    @Html.DisplayNameFor(model => item.ID)
                </a>
            </div>
            <div class="col-12" style="text-align:center">
                <a>
                    @Html.DisplayFor(model => item.ID)
                </a>
            </div>
            <div class="col-12" style="text-align:center">
                <a>
                    @Html.DisplayNameFor(model => item.BillName)
                </a>
            </div>
            <div class="col-12" style="text-align:center">
                <a>
                    @Html.DisplayFor(model => item.BillName)
                </a>
            </div>
            <div class="col-12" style="text-align:center">
                <a>
                    @Html.DisplayNameFor(model => item.NameFood)
                </a>
            </div>
            <div class="col-12" style="text-align:center">
                <a>
                    @Html.DisplayFor(model => item.NameFood)
                </a>
            </div>
            <div class="col-12" style="text-align:center">
                <a>
                    @Html.DisplayNameFor(model => item.Amount)
                </a>
            </div>
            <div class="col-12" style="text-align:center">
                <a>
                    @Html.DisplayFor(model => item.Amount)
                </a>
            </div>
            <div class="col-12" style="text-align:center">
                <a>
                    @Html.DisplayNameFor(model => item.UnitPrice)
                </a>
            </div>
            <div class="col-12" style="text-align:center">
                <a>
                    @Html.DisplayFor(model => item.UnitPrice)
                </a>
            </div>
        }
    }

    <div class="col-12" style="text-align:center">
        <a>
            Chúc quý khách ngon miệng!
        </a>
    </div>

</div>
<p>
    <a href="~/Admin/Bill/Index" class="btn btn-default" style="margin-left:10px">Quay lại</a>
</p>

DeAnCNPMNC/DeAnCNPMNC/Areas/Admin/Views/Bill/DetailsNV.cshtml
@model DeAnCNPMNC.Models.DetailBill

@{
    ViewBag.Title = "DetailsNV";
    Layout = "~/Areas/Admin/Views/Shared/_layoutquanly.cshtml";
}

<div>
    <h1 class="col-12" style="text-align:center">Chi tiết hóa đơn</h1>
    <hr />

    @using (var context = new DeAnCNPMNC.Models.CNPMFastFoodEntities())
    {
        foreach (var item in context.DetailBills.Where(s => s.BillName.ToString().Contains(Model.ID.ToString())).ToList())
        {
            <div class="col-12" style="text-align:center">
                <a>
                    @Html.DisplayNameFor(model => item.ID)
                </a>
            </div>
            <div class="col-12" style="text-align:center">
                <a>
                    @Html.DisplayFor(model => item.ID)
                </a>
            </div>
            <div class="col-12" style="text-align:center">
                <a>
                    @Html.DisplayNameFor(model => item.BillName)
                </a>
            </div>
            <div class="col-12" style="text-align:center">
                <a>
                    @Html.DisplayFor(model => item.BillName)
                </a>
            </div>
            <div class="col-12" style="text-align:center">
                <a>
                    @Html.DisplayNameFor(model => item.NameFood)
                </a>
            </div>
            <div class="col-12" style="text-align:center">
                <a>
                    @Html.DisplayFor(model => item.NameFood)
                </a>
            </div>
            <div class="col-12" style="text-align:center">
                <a>
                    @Html.DisplayNameFor(model => item.Amount)
                </a>
            </div>
            <div class="col-12" style="text-align:center">
                <a>
                    @Html.DisplayFor(model => item.Amount)
                </a>
            </div>
            <div class="col-12" style="text-align:center">
                <a>
                    @Html.DisplayNameFor(model => item.UnitPrice)
                </a>
            </div>
            <div class="col-12" style="text-align:center">
                <a>
                    @Html.DisplayFor(model => item.UnitPrice)
                </a>
            </div>
        }
    }

    <div class="col-12" style="text-align:center">
        <a>
            Chúc quý khách ngon miệng!
        </a>
    </div>

</div>
<p>
    <a href="~/Admin/Bill/DSBill" class="btn btn-default" style="margin-left:10px">Quay lại</a>
</p>

DeAnCNPMNC/DeAnCNPMNC/Areas/Admin/Views/Bill/EditBill.cshtml
@model DeAnCNPMNC.Models.Bill

@{
    ViewBag.Title = "EditBill";
    Layout = "~/Areas/Admin/Views/Shared/_layoutquanly.cshtml";
}

<h2>EditBill</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Bill</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.IDBill, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IDBill, new { htmlAttributes = new { @readonly = "readonly", @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IDBill, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateOrder, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateOrder, new { htmlAttributes = new { @readonly = "readonly", @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateOrder, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AccCustomer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AccCustomer, new { htmlAttributes = new { @readonly = "readonly", @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AccCustomer, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CouponName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CouponName, new { htmlAttributes = new { @readonly = "readonly", @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CouponName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TotalBill, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TotalBill, new { htmlAttributes = new { @readonly = "readonly", @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TotalBill, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AddressCus, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AddressCus, new { htmlAttributes = new { @readonly = "readonly", @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AddressCus, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Status, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DeAnCNPMNC/DeAnCNPMNC/Areas/Admin/Views/Bill/Index.cshtml
@model IEnumerable<DeAnCNPMNC.Models.Bill>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_layoutquanly.cshtml";
}

<h2>Index</h2>

@using (Html.BeginForm("Index", "Bill", FormMethod.Post))
{
    <h5>
        Từ ngày: <input type="date" name="date" value="@Session["date"]" /> Đến ngày: <input type="date" name="date1" value="@Session["date1"]" /> <input type="submit" value="Tìm kiếm" />
    </h5>
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.DateOrder)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AccCustomer)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AddressCus)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TotalBill)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.DateOrder)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AccCustomer)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AddressCus)
            </td>
            <td>
                @if (item.Status == true)
                {
                    <a>Đã phục vụ</a>
                }
                else
                {
                    <a>Chưa phục vụ</a>
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TotalBill)
            </td>
            <td>
                @Html.ActionLink("Chi tiết hóa đơn", "DetailsAD", new { Id = item.IDBill })
            </td>
        </tr>
    }
</table>

<div class="col-12" style="text-align:right">
    <a>Tổng doanh thu: </a>
    <input type="text" name="Total" value="@Model.Sum(s=>s.TotalBill)" disabled />
</div>
@using (Html.BeginForm("Tranfer", "Bill", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div style="text-align:right; margin-right:200px; padding-top:20px">
        <p>
            <input type="submit" value="Lưu doanh thu" />
        </p>
    </div>

}