DeAnCNPMNC/DeAnCNPMNC/Models/CategoryCustomer.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeAnCNPMNC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class CategoryCustomer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CategoryCustomer()
        {
            this.Customers = new HashSet<Customer>();
        }
        [NotMapped]
        public List<CategoryCustomer> ListCateCus { get; set; }
        [Display(Name = "Mã loại khách hàng: ")]
        [Required(ErrorMessage = "Mã loại khách hàng không được để trống ...")]
        public string IDCateCus { get; set; }
        [Display(Name = "Tên loại khách hàng: ")]
        [Required(ErrorMessage = "Tên loại khách hàng không được để trống ...")]
        public string NameCateCus { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer> Customers { get; set; }
    }
}

DeAnCNPMNC/DeAnCNPMNC/Areas/Admin/Controllers/CategoryCustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DeAnCNPMNC.Models;

namespace DeAnCNPMNC.Areas.Admin.Controllers
{
    [Authorize(Roles = "AD")]
    public class CategoryCustomerController : Controller
    {
        // GET: Admin/CategoryCus
        CNPMFastFoodEntities database = new CNPMFastFoodEntities();
        [Authorize(Roles = "AD")]
        public ActionResult Index(string _name)
        {
            if (_name == null)
            {
                return View(database.CategoryCustomers.ToList());
            }
            else
            {
                return View(database.CategoryCustomers.Where(s => s.IDCateCus.Contains(_name)).ToList());
            }
        }
        [Authorize(Roles = "AD")]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(CategoryCustomer catecus)
        {
            if(ModelState.IsValid)
            {
                var isICateCuslAlreadyExists = database.CategoryCustomers.Any(x => x.IDCateCus == catecus.IDCateCus);
                if (isICateCuslAlreadyExists)
                {
                    ModelState.AddModelError(string.Empty, "ID này đã tồn tại");
                    return View(catecus);
                }
                database.CategoryCustomers.Add(catecus);
                database.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(catecus);
        }
        [Authorize(Roles = "AD")]
        public ActionResult Details(string id)
        {
            return View(database.CategoryCustomers.Where(s => s.IDCateCus == id).FirstOrDefault());
        }
        [Authorize(Roles = "AD")]
        public ActionResult Edit(string id)
        {
            return View(database.CategoryCustomers.Where(s => s.IDCateCus == id).FirstOrDefault());
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(CategoryCustomer catecus)
        {
            if(ModelState.IsValid)
            {
                database.Entry(catecus).State = System.Data.Entity.EntityState.Modified;
                database.SaveChanges();
                return RedirectToAction("Index");

            }
            return View(catecus);
        }
        //[Authorize(Roles = "AD")]
        //public ActionResult Delete(string id)
        //{
        //    return View(database.CategoryCustomers.Where(s => s.IDCateCus == id).FirstOrDefault());
        //}
        //[HttpPost]
        //public ActionResult Delete(string id, CategoryCustomer catecus)
        //{
        //    try
        //    {
        //        catecus = database.CategoryCustomers.Where(s => s.IDCateCus == id).FirstOrDefault();
        //        database.CategoryCustomers.Remove(catecus);
        //        database.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    catch
        //    {
        //        return Content("this data is using in other table, Error delete !");
        //    }
        //}
    }
}

DeAnCNPMNC/DeAnCNPMNC/Areas/Admin/Views/CategoryCustomer/Create.cshtml
@model DeAnCNPMNC.Models.CategoryCustomer

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_layoutquanly.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "CategoryCustomer", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CategoryCustomer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.IDCateCus, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IDCateCus, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IDCateCus, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NameCateCus, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NameCateCus, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NameCateCus, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DeAnCNPMNC/DeAnCNPMNC/Areas/Admin/Views/CategoryCustomer/Delete.cshtml
@model DeAnCNPMNC.Models.CategoryCustomer

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_layoutquanly.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CategoryCu</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.IDCateCus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IDCateCus)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NameCateCus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NameCateCus)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

DeAnCNPMNC/DeAnCNPMNC/Areas/Admin/Views/CategoryCustomer/Details.cshtml
@model DeAnCNPMNC.Models.CategoryCustomer

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_layoutquanly.cshtml";
}

<h2>Details</h2>

<div>
    <h4>CategoryCu</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.IDCateCus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IDCateCus)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NameCateCus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NameCateCus)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.IDCateCus }) |
    @Html.ActionLink("Back to List", "Index")
</p>

DeAnCNPMNC/DeAnCNPMNC/Areas/Admin/Views/CategoryCustomer/Edit.cshtml
@model DeAnCNPMNC.Models.CategoryCustomer

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_layoutquanly.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "CategoryCustomer", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CategoryCustomer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.IDCateCus, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IDCateCus, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IDCateCus, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NameCateCus, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NameCateCus, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NameCateCus, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DeAnCNPMNC/DeAnCNPMNC/Areas/Admin/Views/CategoryCustomer/Index.cshtml
@model IEnumerable<DeAnCNPMNC.Models.CategoryCustomer>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_layoutquanly.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.IDCateCus)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NameCateCus)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.IDCateCus)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NameCateCus)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.IDCateCus }) |
            @Html.ActionLink("Details", "Details", new { id = item.IDCateCus }) @*|
            @Html.ActionLink("Delete", "Delete", new { id = item.IDCateCus })*@
        </td>
    </tr>
}

</table>