DeAnCNPMNC/DeAnCNPMNC/Controllers/ProfileCusController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DeAnCNPMNC.Models;

namespace DeAnCNPMNC.Controllers
{
    public class ProfileCusController : Controller
    {
        CNPMFastFoodEntities database = new CNPMFastFoodEntities();
        // GET: ProfileCus
        public ActionResult Index(Customer cus)
        {
            Session["AccountCustomer"] = cus.AccountCustomer;
            Session["NameCustomer"] = cus.NameCustomer;
            Session["PassCustomer"] = cus.PassCustomer;
            Session["ImageCustomer"] = cus.ImageCustomer;
            Session["DateOfBirthCustomer"] = cus.DateOfBirthCustomer;
            Session["PhoneCustomer"] = cus.PhoneCustomer;
            Session["EmailCustomer"] = cus.EmailCustomer;
            Session["AddressCustomer"] = cus.AddressCustomer;
            Session["SexCustomer"] = cus.SexCustomer;
            Session["NameCateCustomer"] = cus.NameCateCustomer;
            Session["Point"] = cus.Point;
            return RedirectToAction("Index", "Home");  
        }
        //public ActionResult Profile(string id, Customer cus)
        //{
        //    if (Session["AccountCustomer"] == cus.AccountCustomer)
        //    {
        //        return View(database.Customers.Where(s => s.AccountCustomer == id).FirstOrDefault());
        //    }
        //    else
        //    {
        //        return View("Index");
        //    }
            
        //}
        public ActionResult Details(string id)
        {
            id = (string)Session["AccountCustomer"];
            return View(database.Customers.Where(s => s.AccountCustomer == id).FirstOrDefault());
        }
        public ActionResult Edit(string id)
        {
            id = (string)Session["AccountCustomer"];
            return View(database.Customers.Where(s => s.AccountCustomer == id).FirstOrDefault());
        }
        [HttpPost]
        public ActionResult Edit(Customer cus)
        {
            database.Entry(cus).State = System.Data.Entity.EntityState.Modified;
            try
            {
                if (cus.UploadImage != null)
                {
                    string filename = Path.GetFileNameWithoutExtension(cus.UploadImage.FileName);
                    string extent = Path.GetExtension(cus.UploadImage.FileName);
                    filename = filename + extent;
                    cus.ImageCustomer = "~/Content/images/" + filename;
                    cus.UploadImage.SaveAs(Path.Combine(Server.MapPath("~/Content/images/"), filename));
                }
                database.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }

        }
    }
}

DeAnCNPMNC/DeAnCNPMNC/Views/Shared/LayoutProfile.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>MyResume Bootstrap Template - Index</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="~/Assets/Profile/img/favicon.png" rel="icon">
    <link href="~/Assets/Profile/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="~/Assets/Profile/vendor/aos/aos.css" rel="stylesheet">
    <link href="~/Assets/Profile/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/Assets/Profile/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="~/Assets/Profile/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="~/Assets/Profile/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
    <link href="~/Assets/Profile/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="~/Assets/Profile/css/style.css" rel="stylesheet">

    <!-- =======================================================
    * Template Name: MyResume - v4.3.0
    * Template URL: https://bootstrapmade.com/free-html-bootstrap-template-my-resume/
    * Author: BootstrapMade.com
    * License: https://bootstrapmade.com/license/
    ======================================================== -->
</head>

<body>
    @RenderBody()
    <!-- Vendor JS Files -->
    <script src="~/Assets/Profile/vendor/aos/aos.js"></script>
    <script src="~/Assets/Profile/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/Assets/Profile/vendor/glightbox/js/glightbox.min.js"></script>
    <script src="~/Assets/Profile/vendor/isotope-layout/isotope.pkgd.min.js"></script>
    <script src="~/Assets/Profile/vendor/php-email-form/validate.js"></script>
    <script src="~/Assets/Profile/vendor/purecounter/purecounter.js"></script>
    <script src="~/Assets/Profile/vendor/swiper/swiper-bundle.min.js"></script>
    <script src="~/Assets/Profile/vendor/typed.js/typed.min.js"></script>
    <script src="~/Assets/Profile/vendor/waypoints/noframework.waypoints.js"></script>

    <!-- Template Main JS File -->
    <script src="~/Assets/Profile/js/main.js"></script>

</body>

DeAnCNPMNC/DeAnCNPMNC/Views/Shared/_Layout.cshtml
@using DeAnCNPMNC.Models;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>DacVu-Shop</title>
    <link rel="icon" type="image/x-icon" href="/Assets/assets/img/favicon.ico" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v5.15.1/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="/Assets/layout/css/styles.css" rel="stylesheet" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body id="page-top">
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav" style="background-color:#F8AA0A">
        <div class="container">
            <a class="navbar-brand js-scroll-trigger" href="#page-top"><img src="~/Assets/layout/assets/img/navbar-logo.svg" alt="" /></a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                Menu
                <i class="fas fa-bars ml-1"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav text-uppercase ml-auto">
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#services">HOME</a></li>
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#portfolio">MENU</a></li>
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#about">COMBO</a></li>
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#team">DISCOUNT</a></li>
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#contact">SUPPORT</a></li>
                    <!-- Nav Item - gio hang -->
                    <li>
                        <span>
                            <a href="/ShopingCart/ShowCart">
                                <img src="@Url.Content("~/Content/Images2/cart.png")" style="height:30px;width:30px;margin-top:10px;" />

                            </a>
                        </span>
                        @Html.Action("BagCart", "ShopingCart")
                    </li>
                    <!-- Nav Item - User Information -->
                    <li class="nav-item dropdown no-arrow">
                        <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <span class="mr-2 d-none d-lg-inline text-gray-600 small">Douglas McGee</span>
                            <img class="img-profile rounded-circle"
                                 src="img/undraw_profile.svg">
                        </a>
                        <!-- Dropdown - User Information -->
                        <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                             aria-labelledby="userDropdown">
                            <a class="dropdown-item" href="#">
                                <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                                Profile
                            </a>
                            <a class="dropdown-item" href="#">
                                <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                                Settings
                            </a>
                            <a class="dropdown-item" href="#">
                                <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                                Activity Log
                            </a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                                <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                Logout
                            </a>
                        </div>
                    </li>

                </ul>
            </div>
        </div>
    </nav>
    @RenderBody()
    <!-- Contact-->
    <section class="page-section" id="contact">
        <div class="container">
            <div class="text-center">
                <h2 class="section-heading text-uppercase">Contact Us</h2>
                <h3 class="section-subheading text-muted">Lorem ipsum dolor sit amet consectetur.</h3>
            </div>
            <form id="contactForm" name="sentMessage" novalidate="novalidate">
                <div class="row align-items-stretch mb-5">
                    <div class="col-md-6">
                        <div class="form-group">
                            <input class="form-control" id="name" type="text" placeholder="Your Name *" required="required" data-validation-required-message="Please enter your name." />
                            <p class="help-block text-danger"></p>
                        </div>
                        <div class="form-group">
                            <input class="form-control" id="email" type="email" placeholder="Your Email *" required="required" data-validation-required-message="Please enter your email address." />
                            <p class="help-block text-danger"></p>
                        </div>
                        <div class="form-group mb-md-0">
                            <input class="form-control" id="phone" type="tel" placeholder="Your Phone *" required="required" data-validation-required-message="Please enter your phone number." />
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group form-group-textarea mb-md-0">
                            <textarea class="form-control" id="message" placeholder="Your Message *" required="required" data-validation-required-message="Please enter a message."></textarea>
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                </div>
                <div class="text-center">
                    <div id="success"></div>
                    <button class="btn btn-primary btn-xl text-uppercase" id="sendMessageButton" type="submit">Send Message</button>
                </div>
            </form>
        </div>
    </section>
    <!-- Footer-->
    <footer class="footer py-4">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-4 text-lg-left">Copyright © Your Website 2020</div>
                <div class="col-lg-4 my-3 my-lg-0">
                    <a class="btn btn-dark btn-social mx-2" href="#!"><i class="fab fa-twitter"></i></a>
                    <a class="btn btn-dark btn-social mx-2" href="#!"><i class="fab fa-facebook-f"></i></a>
                    <a class="btn btn-dark btn-social mx-2" href="#!"><i class="fab fa-linkedin-in"></i></a>
                </div>
                <div class="col-lg-4 text-lg-right">
                    <a class="mr-3" href="#!">Privacy Policy</a>
                    <a href="#!">Terms of Use</a>
                </div>
            </div>
        </div>
    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Third party plugin JS-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
    <!-- Contact form JS-->
    <script src="/Assets/layout/assets/mail/jqBootstrapValidation.js"></script>
    <script src="/Assets/layout/assets/mail/contact_me.js"></script>
    <!-- Core theme JS-->
    <script src="/Assets/layout/js/scripts.js"></script>
</body>
</html>

DeAnCNPMNC/DeAnCNPMNC/Views/Shared/_LayoutPage1.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="generator" content="">
    <link href="~/Assets/layout/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet">
    <link href="~/Assets/layout/css/style.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Dosis:200,300,400,500,600,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto:200,300,400,500,600,700" rel="stylesheet">
    <script src="https://kit.fontawesome.com/88d882a928.js" crossorigin="anonymous"></script>
    <link href="~/fonts/FONTDEP.COM-BACKSLASH.TTF" rel="stylesheet" />
    <style>
        .item.header {
            background-image: url(/Assets/layout/images/Background2.jpg);
            background-repeat: no-repeat;
            background-position: 0% top;
            background-size: cover;
            background-attachment: scroll;
            background-color: rgba(0,0,0,0);
        }

        .subtext-image {
            font-family: Backslash
        }

        .dropbtn {
            margin-top: 10px;
            background-color: white;
            color: white;
            font-size: 16px;
            border: none;
            cursor: pointer;
        }

        /* The container <div> - needed to position the dropdown content */
        .dropdown {
            position: relative;
            display: inline-block;
        }

        /* Dropdown Content (Hidden by Default) */
        .dropdown-content {
            display: none;
            position: absolute;
            background-color: whitesmoke;
            min-width: 160px;
            box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
            z-index: 1;
            right: 0;
        }

            /* Links inside the dropdown */
            .dropdown-content a {
                color: black;
                padding: 5px 10px;
                text-decoration: none;
                display: block;
            }

                /* Change color of dropdown links on hover */
                .dropdown-content a:hover {
                    background-color: #f1f1f1
                }

        /* Show the dropdown menu on hover */
        .dropdown:hover .dropdown-content {
            display: block;
        }

        /* Change the background color of the dropdown button when the dropdown content is shown */
        .dropdown:hover .dropbtn {
            background-color: whitesmoke;
        }
    </style>
</head>

<body>


    <!-- HEADER =============================-->
    <header class="item header margin-top-0">
        <div class="wrapper">
            <nav role="navigation" class="navbar navbar-white navbar-embossed navbar-lg navbar-fixed-top">
                <div class="container">
                    <div class="navbar-header">
                        <button data-target="#navbar-collapse-02" data-toggle="collapse" class="navbar-toggle" type="button">
                            <i class="fa fa-bars"></i>
                            <span class="sr-only">Toggle navigation</span>
                        </button>
                        <a href="index.html" class="navbar-brand brand" style="font-family:Backslash"> AGENT FAST FOOD </a>
                    </div>
                    <div id="navbar-collapse-02" class="collapse navbar-collapse">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="propClone"><a href="~/Home/Index">Home</a></li>
                            <li class="propClone"><a href="~/Menu/Index">Menu</a></li>
                            <li class="propClone"><a href="~/Introduce/Support">Support</a></li>
                            <li class="propClone"><a href="~/CouponCustomer/Index">Discount</a></li>
                            <li class="propClone"><a href="~/Introduce/Review">Preview</a></li>
                            <li>
                                <span>
                                    <a href="/ShopingCart/ShowCart">
                                        <img src="@Url.Content("~/Assets/layout/images/cart.png")" style="height:30px; width:30px; margin-top:22px;" />
                                    </a>
                                </span>
                                @Html.Action("BagCart", "ShopingCart")
                            </li>
                            @if (Session["AccountCustomer"] != null)
                            {
                                <li class="propClone">
                                    <div class="dropdown">
                                        <button class="dropbtn">
                                            <img style="border-radius: 50%; border: 2px solid #a1a1a1; height: 50px; text-align: center; width: 50px;" src="@Url.Content((string)Session["ImageCustomer"])" />
                                        </button>
                                        <div class="dropdown-content">
                                            <a>Hello: @Session["AccountCustomer"]</a>
                                            <a>@Html.ActionLink("Profile", "Details", "ProfileCus")</a>
                                            <a>@Html.ActionLink("Logout", "Logout", "LoginCus")</a>

                                        </div>
                                    </div>
                                </li>
                            }
                            else
                            {
                                <li class="propClone">
                                    <div class="dropdown">
                                        <button class="dropbtn"><img src="~/Assets/layout/images/Cus.png" /></button>
                                        <div class="dropdown-content">
                                            <a>@Html.ActionLink("Đăng nhập", "index", "LoginCus")</a>
                                            <a>@Html.ActionLink("Đăng kí", "SignUp", "LoginCus")</a>
                                        </div>
                                    </div>
                                </li>

                            }
                        </ul>
                    </div>
                </div>
            </nav>
            <div class="container">
                <div class="row">
                    <div class="col-md-12 text-center">
                        <div class="text-homeimage">
                            <div class="maintext-image" data-scrollreveal="enter top over 1.5s after 0.1s">
                                Wellcome to
                            </div>
                            <div class="subtext-image" data-scrollreveal="enter bottom over 1.7s after 0.3s">
                                Agent Fast Food
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>




    <!-- LATEST ITEMS =============================-->
    @RenderBody()


    <!-- BUTTON =============================-->
    <!-- AREA =============================-->
    <!-- TESTIMONIAL =============================-->
    <!-- CALL TO ACTION =============================-->
    


    <!-- FOOTER =============================-->
    <div class="footer text-center">
        <div class="container">
            <div class="row">
                <ul class="social-iconsfooter">
                    <li><a href="#"><i class="fa fa-phone"></i></a></li>
                    <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                    <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                    <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                    <li><a href="#"><i class="fa fa-pinterest"></i></a></li>
                </ul>
                <p>
                    &copy; 2017 Your Website Name<br />
                </p>
                <div class="credits">
                    <!-- All the links in the footer should remain intact. -->
                    <!-- You can delete the links only if you purchased the pro version. -->
                    <!-- Licensing information: https://bootstrapmade.com/license/ -->
                    <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/restaurantly-restaurant-template/ -->
                    Designed by <b style="font-family:'Script MT' ">Huy & Tường</b>
                </div>
            </div>
        </div>
    </div>

    <!-- SCRIPTS =============================-->
    <script src="~/Assets/layout/js/jquery-.js"></script>
    <script src="~/Assets/layout/js/bootstrap.min.js"></script>
    <script src="~/Assets/layout/js/anim.js"></script>
    <script>
        //----HOVER CAPTION---//
        jQuery(document).ready(function ($) {
            $('.fadeshop').hover(
                function () {
                    $(this).find('.captionshop').fadeIn(150);
                },
                function () {
                    $(this).find('.captionshop').fadeOut(150);
                }
            );
        });
    </script>

</body>
</html>