DeAnCNPMNC/DeAnCNPMNC/Models/CategoryFood.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeAnCNPMNC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class CategoryFood
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CategoryFood()
        {
            this.Foods = new HashSet<Food>();
        }
        [NotMapped]
        public List<CategoryFood> ListCate { get; set; }
        [Display(Name = "Mã loại món ăn: ")]
        [Required(ErrorMessage = "Mã loại món ăn không được để trống ...")]
        public string IDCFood { get; set; }
        [Display(Name = "Tên loại món ăn: ")]
        [Required(ErrorMessage = "Tên loại món ăn không được để trống ...")]
        public string NameCategoryFood { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Food> Foods { get; set; }
    }
}

DeAnCNPMNC/DeAnCNPMNC/Areas/Admin/Controllers/CategoryFoodController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DeAnCNPMNC.Models;

namespace DeAnCNPMNC.Areas.Admin.Controllers
{
    [Authorize(Roles = "AD")]
    public class CategoryFoodController : Controller
    {
        CNPMFastFoodEntities database = new CNPMFastFoodEntities();
        // GET: Admin/CategoryFood
        [Authorize(Roles = "AD")]
        public ActionResult Index(string _name)
        {
            if (_name == null)
            {
                return View(database.CategoryFoods.ToList());
            }
            else
            {
                return View(database.CategoryFoods.Where(s => s.NameCategoryFood.Contains(_name)).ToList());
            }
        }
        [Authorize(Roles = "AD")]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(CategoryFood catefood)
        {
            if(ModelState.IsValid)
            {
                var isICateFoodlAlreadyExists = database.CategoryFoods.Any(x => x.IDCFood == catefood.IDCFood);
                if(isICateFoodlAlreadyExists)
                {
                    ModelState.AddModelError(string.Empty, "ID này đã tồn tại");
                    return View(catefood);
                }
                database.CategoryFoods.Add(catefood);
                database.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(catefood);
        }
        [Authorize(Roles = "AD")]
        public ActionResult Details(string id)
        {
            return View(database.CategoryFoods.Where(s => s.IDCFood == id).FirstOrDefault());
        }
        [Authorize(Roles = "AD")]
        public ActionResult Edit(string id)
        {
            return View(database.CategoryFoods.Where(s => s.IDCFood == id).FirstOrDefault());
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(CategoryFood catefood)
        {
            if(ModelState.IsValid)
            {
                database.Entry(catefood).State = System.Data.Entity.EntityState.Modified;
                database.SaveChanges();
                return RedirectToAction("Index");

            }
            return View(catefood);
        }
        //[Authorize(Roles = "AD")]
        //public ActionResult Delete(string id)
        //{
        //    return View(database.CategoryFoods.Where(s => s.IDCFood == id).FirstOrDefault());
        //}
        //[HttpPost]
        //public ActionResult Delete(string id,CategoryFood catefood)
        //{
        //    try
        //    {
        //        catefood = database.CategoryFoods.Where(s => s.IDCFood == id).FirstOrDefault();
        //        database.CategoryFoods.Remove(catefood);
        //        database.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    catch
        //    {
        //        return Content("this data is using in other table, Error delete !");
        //    }
        //}
    }
}

DeAnCNPMNC/DeAnCNPMNC/Areas/Admin/Views/CategoryFood/Create.cshtml
@model DeAnCNPMNC.Models.CategoryFood

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_layoutquanly.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "CategoryFood", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CategoryFood</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.IDCFood, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IDCFood, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IDCFood, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NameCategoryFood, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NameCategoryFood, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NameCategoryFood, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DeAnCNPMNC/DeAnCNPMNC/Areas/Admin/Views/CategoryFood/Delete.cshtml
@model DeAnCNPMNC.Models.CategoryFood

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_layoutquanly.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CategoryFood</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.IDCFood)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IDCFood)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NameCategoryFood)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NameCategoryFood)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

DeAnCNPMNC/DeAnCNPMNC/Areas/Admin/Views/CategoryFood/Details.cshtml
@model DeAnCNPMNC.Models.CategoryFood

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_layoutquanly.cshtml";
}

<h2>Details</h2>

<div>
    <h4>CategoryFood</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.IDCFood)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IDCFood)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.NameCategoryFood)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NameCategoryFood)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.IDCFood }) |
    @Html.ActionLink("Back to List", "Index")
</p>

DeAnCNPMNC/DeAnCNPMNC/Areas/Admin/Views/CategoryFood/Edit.cshtml
@model DeAnCNPMNC.Models.CategoryFood

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_layoutquanly.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "CategoryFood", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CategoryFood</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.IDCFood, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IDCFood, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IDCFood, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NameCategoryFood, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NameCategoryFood, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NameCategoryFood, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DeAnCNPMNC/DeAnCNPMNC/Areas/Admin/Views/CategoryFood/Index.cshtml
@model IEnumerable<DeAnCNPMNC.Models.CategoryFood>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_layoutquanly.cshtml";
}

<h2>Category Food</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model=>model.IDCFood)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NameCategoryFood)
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(model=>item.IDCFood)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NameCategoryFood)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.IDCFood }) |
            @Html.ActionLink("Details", "Details", new { id=item.IDCFood }) @*|
            @Html.ActionLink("Delete", "Delete", new { id=item.IDCFood })*@
        </td>
    </tr>
}

</table>